# this is the default cloudbuild.
timeout: 1200s
steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - 'build'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/kubemacs:${_GIT_TAG}'
      - '--build-arg'
      - 'IMAGE_ARG=gcr.io/${PROJECT_ID}/kubemacs:${_GIT_TAG}'
      - '.'
images:
  - 'gcr.io/${PROJECT_ID}/kubemacs:${_GIT_TAG}'
substitutions:
  _GIT_TAG: '12345'
options:
  substitution_option: 'ALLOW_LOOSE'
