apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - manifests/nginx-ingress
  - manifests/tmate
resources:
  - manifests/configuration.yaml
  - manifests/statefulset.yaml
  - manifests/service-account.yaml
  - manifests/cluster-role-binding.yaml
  - manifests/tilt-service.yaml
configMapGenerator:
- name: kubemacs-configuration
  behavior: merge
  literals:
  - TZ=Pacific/Auckland
  - GIT_EMAIL=
  - GIT_NAME=
  - INIT_DEFAULT_DIR=/home/ii
  - INIT_DEFAULT_REPOS_FOLDER=/home/ii/Projects
  - INIT_DEFAULT_REPOS=
  - INIT_ORG_FILE=
# configMapGenerator:
#   - name: kubemacs-options
#     env: kubemacs-options
